// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        *int64                 `protobuf:"varint,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_proto_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendRequest) GetCursor() int64 {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return 0
}

func (x *RecommendRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumIds      []int64                `protobuf:"varint,1,rep,packed,name=album_ids,json=albumIds,proto3" json:"album_ids,omitempty"`
	NextCursor    *int64                 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	HasNext       bool                   `protobuf:"varint,3,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_proto_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetAlbumIds() []int64 {
	if x != nil {
		return x.AlbumIds
	}
	return nil
}

func (x *RecommendResponse) GetNextCursor() int64 {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return 0
}

func (x *RecommendResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_proto_feed_proto protoreflect.FileDescriptor

const file_proto_feed_proto_rawDesc = "" +
	"\n" +
	"\x10proto/feed.proto\x12\x04feed\"g\n" +
	"\x10RecommendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\x03H\x00R\x06cursor\x88\x01\x01\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04sizeB\t\n" +
	"\a_cursor\"\x81\x01\n" +
	"\x11RecommendResponse\x12\x1b\n" +
	"\talbum_ids\x18\x01 \x03(\x03R\balbumIds\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\x03H\x00R\n" +
	"nextCursor\x88\x01\x01\x12\x19\n" +
	"\bhas_next\x18\x03 \x01(\bR\ahasNextB\x0e\n" +
	"\f_next_cursor2T\n" +
	"\x10RecommendService\x12@\n" +
	"\rRecommendFeed\x12\x16.feed.RecommendRequest\x1a\x17.feed.RecommendResponseB1\n" +
	"\x14com.snapy.proto.feedB\tFeedProtoP\x01Z\fgo/feed;feedb\x06proto3"

var (
	file_proto_feed_proto_rawDescOnce sync.Once
	file_proto_feed_proto_rawDescData []byte
)

func file_proto_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)))
	})
	return file_proto_feed_proto_rawDescData
}

var file_proto_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_feed_proto_goTypes = []any{
	(*RecommendRequest)(nil),  // 0: feed.RecommendRequest
	(*RecommendResponse)(nil), // 1: feed.RecommendResponse
}
var file_proto_feed_proto_depIdxs = []int32{
	0, // 0: feed.RecommendService.RecommendFeed:input_type -> feed.RecommendRequest
	1, // 1: feed.RecommendService.RecommendFeed:output_type -> feed.RecommendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_feed_proto_init() }
func file_proto_feed_proto_init() {
	if File_proto_feed_proto != nil {
		return
	}
	file_proto_feed_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_feed_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_proto = out.File
	file_proto_feed_proto_goTypes = nil
	file_proto_feed_proto_depIdxs = nil
}
